# Nacos 配置: payment-service.yaml
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_payment?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 2096035290
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20

# 支付配置
payment:
  mock:
    success-rate: 1.0

